# Generated by Django 2.2.4 on 2020-02-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roast_number', models.IntegerField(unique=True)),
                ('date', models.DateTimeField(verbose_name='Roast Date')),
                ('notes', models.CharField(max_length=1000)),
                ('dev_percent', models.IntegerField()),
                ('weight_percent', models.IntegerField()),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Coffee')),
            ],
        ),
        migrations.CreateModel(
            name='RoastLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoastDataPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_temp', models.IntegerField()),
                ('exh_temp', models.IntegerField()),
                ('time', models.TimeField()),
                ('note', models.CharField(max_length=500)),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Roast')),
            ],
        ),
        migrations.AddField(
            model_name='roast',
            name='roast_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.RoastLevel'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='suggested_roast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.RoastLevel'),
        ),
    ]
